"use client";
import { useState } from 'react';

export default function ReportButton() {
  const [reportContent, setReportContent] = useState<string | null>(null);
  const [reportId, setReportId] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const generateReport = () => {
    setIsGenerating(true);

    // Simulate brief processing delay
    setTimeout(() => {
      const now = new Date();
      const newReportId = `REP-${now.getFullYear()}-${String(Math.floor(Math.random() * 900000) + 100000)}`;

      const content = `Date: ${now.toLocaleString()}

Report ID: ${newReportId}
Generated By: AI-Driven Disease Outbreak Surveillance System
County: Nairobi County
Reporting Period: March 1, 2026 – March 14, 2026

Summary:
During the reporting period, the LSTM prediction model analysed daily
disease case counts alongside environmental data (temperature, rainfall,
humidity) for Nairobi County. A total of 14 prediction cycles were
completed with an average risk score of 42.3%.

Risk Assessment:
Current Outbreak Risk Score: 58.7% — MODERATE RISK
Peak Risk Score (period): 71.2% — HIGH RISK (March 9, 2026)
Lowest Risk Score (period): 28.4% — LOW RISK (March 3, 2026)
Model Confidence Level: 87.4%

Disease Breakdown (Top 3 by case count):
1. Acute Respiratory Infections — 312 cases
2. Typhoid Fever               — 187 cases
3. Malaria                     — 124 cases

Alerts Dispatched:
Total Alerts: 2
Alert 1: March 9, 2026 — Risk score 71.2% exceeded threshold (65%)
         Status: ACKNOWLEDGED by Health Officer
Alert 2: March 11, 2026 — Risk score 67.8% exceeded threshold (65%)
         Status: RESOLVED

Recommendation:
Risk levels remain elevated above the seasonal baseline. The Ministry
of Health is advised to increase surveillance frequency at Pumwani
Maternity Hospital and Mbagathi County Referral Hospital and to review
cholera and typhoid containment protocols for the next 14-day period.`;

      setReportContent(content);
      setReportId(newReportId);
      setIsGenerating(false);
    }, 800);
  };

  return (
    <>
      <button
        onClick={generateReport}
        disabled={isGenerating}
        className="bg-blue-600 text-white px-4 py-2 rounded-lg font-medium hover:bg-blue-700 transition-all disabled:bg-blue-400"
      >
        {isGenerating ? "AI Processing..." : "Generate Report"}
      </button>

      {/* MODAL POPUP */}
      {reportContent && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-3xl p-8 max-w-2xl w-full shadow-2xl animate-in zoom-in duration-300">
            <div className="flex justify-between items-start mb-6">
              <div>
                <p className="text-xs font-bold text-blue-600 uppercase tracking-widest mb-1">
                  Outbreak Surveillance Report
                </p>
                <h2 className="text-2xl font-black text-slate-900">
                  AI-Driven Disease Report
                </h2>
              </div>
              <div className="text-right">
                <span className="text-[10px] font-mono text-slate-400 block mb-1">
                  {reportId}
                </span>
                <span className="px-2 py-1 bg-green-100 text-green-700 text-xs font-bold rounded-md">
                  87.4% Accuracy
                </span>
              </div>
            </div>

            <div className="bg-slate-50 p-5 rounded-2xl mb-8 border border-slate-100 max-h-96 overflow-y-auto">
              <pre className="text-slate-700 text-sm leading-relaxed whitespace-pre-wrap font-mono">
                {reportContent}
              </pre>
            </div>

            <div className="flex gap-4">
              <button
                onClick={() => { setReportContent(null); setReportId(null); }}
                className="flex-1 py-3 bg-slate-100 text-slate-600 rounded-xl font-bold hover:bg-slate-200 transition-all"
              >
                Dismiss
              </button>
              <button
                onClick={() => window.print()}
                className="flex-1 py-3 bg-blue-600 text-white rounded-xl font-bold hover:bg-blue-700 shadow-lg shadow-blue-200 transition-all"
              >
                Print PDF
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}