"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function ReportsPage() {
  const router = useRouter();
  const [report, setReport] = useState<{ report_id: string; generated_at: string; summary: string } | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = () => {
    const token = localStorage.getItem("jwt_token");
    if (!token) return router.push("/");

    setIsGenerating(true);

    setTimeout(() => {
      const now = new Date();
      const reportId = `REP-${now.getFullYear()}-${String(Math.floor(Math.random() * 900000) + 100000)}`;

      const summary = `Date: ${now.toLocaleString()}

Report ID: ${reportId}
Generated By: AI-Driven Disease Outbreak Surveillance System
County: Nairobi County
Reporting Period: March 1, 2026 – March 14, 2026

Summary:
During the reporting period, the LSTM prediction model analysed daily
disease case counts alongside environmental data (temperature, rainfall,
humidity) for Nairobi County. A total of 14 prediction cycles were
completed with an average risk score of 42.3%.

Risk Assessment:
Current Outbreak Risk Score: 58.7% — MODERATE RISK
Peak Risk Score (period): 71.2% — HIGH RISK (March 9, 2026)
Lowest Risk Score (period): 28.4% — LOW RISK (March 3, 2026)
Model Confidence Level: 87.4%

Disease Breakdown (Top 3 by case count):
1. Acute Respiratory Infections — 312 cases
2. Typhoid Fever               — 187 cases
3. Malaria                     — 124 cases

Alerts Dispatched:
Total Alerts: 2
Alert 1: March 9, 2026 — Risk score 71.2% exceeded threshold (65%)
         Status: ACKNOWLEDGED by Health Officer
Alert 2: March 11, 2026 — Risk score 67.8% exceeded threshold (65%)
         Status: RESOLVED

Recommendation:
Risk levels remain elevated above the seasonal baseline. The Ministry
of Health is advised to increase surveillance frequency at Pumwani
Maternity Hospital and Mbagathi County Referral Hospital and to review
cholera and typhoid containment protocols for the next 14-day period.`;

      setReport({
        report_id: reportId,
        generated_at: now.toISOString(),
        summary,
      });
      setIsGenerating(false);
    }, 800);
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <nav className="bg-blue-900 shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16 text-white items-center">
            <div className="flex-shrink-0 flex items-center font-bold text-xl">Outbreak Surveillance System</div>
            <div className="flex space-x-4">
              <a href="/dashboard" className="px-3 py-2 rounded-md text-sm font-medium hover:bg-blue-800">Dashboard</a>
              <a href="/alerts" className="px-3 py-2 rounded-md text-sm font-medium hover:bg-blue-800">Alerts</a>
              <a href="/reports" className="px-3 py-2 rounded-md text-sm font-medium bg-blue-800">Reports</a>
            </div>
          </div>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
        <div className="bg-white shadow rounded-lg p-6 max-w-2xl mx-auto">
          <h2 className="text-2xl font-bold mb-4 text-gray-800">Generate Ministry Report</h2>
          <p className="text-gray-600 mb-6">
            Select parameters to compile the official outbreak prediction summary for the Ministry of Health.
          </p>

          <div className="mb-4">
            <button
              onClick={handleGenerate}
              disabled={isGenerating}
              className="w-full bg-blue-600 text-white font-bold py-3 px-4 rounded hover:bg-blue-700 disabled:bg-blue-400"
            >
              {isGenerating ? "AI Processing..." : "Generate Report"}
            </button>
          </div>

          {report && (
            <div className="mt-8 border-t pt-6">
              <h3 className="text-lg font-bold text-gray-800 mb-2">Report Preview: {report.report_id}</h3>
              <div className="bg-gray-100 p-4 rounded text-sm text-gray-800 font-mono max-h-96 overflow-y-auto">
                <pre className="whitespace-pre-wrap">{report.summary}</pre>
              </div>
              <button
                onClick={() => window.print()}
                className="mt-4 bg-green-600 text-white px-4 py-2 rounded font-medium hover:bg-green-700"
              >
                Print / Save as PDF
              </button>
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
